# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ridge_solver <- function(x, y, lambda) {
    .Call(`_regboost_ridge_solver`, x, y, lambda)
}

metric_fun <- function(y, y_hat, metric) {
    .Call(`_regboost_metric_fun`, y, y_hat, metric)
}

randomRegression_fit <- function(x, y, colsample, subsample, holdvar, n_reg = 500L, lambda = 0.01, weight_metric = "rmse", intercept = TRUE) {
    .Call(`_regboost_randomRegression_fit`, x, y, colsample, subsample, holdvar, n_reg, lambda, weight_metric, intercept)
}

randomRegression_predict <- function(randomReg, xnew) {
    .Call(`_regboost_randomRegression_predict`, randomReg, xnew)
}

rcpparma_hello_world <- function() {
    .Call(`_regboost_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_regboost_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_regboost_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_regboost_rcpparma_bothproducts`, x)
}

